#!/bin/bash

echo "Removing ONNX Runtime dependencies..."
if [ -d "/usr/local/include/onnxruntime" ]; then
  rm -rf /usr/local/include/onnxruntime
fi

for file in /usr/local/lib/libonnxruntime*; do
  if [ -f "$file" ] && [ -s "$file" ]; then
    rm -f "$file"
  fi
done

if [ -f "/usr/local/lib/pkgconfig/onnxruntime.pc" ]; then
  rm -f /usr/local/lib/pkgconfig/onnxruntime.pc
fi
