#!/bin/bash

echo "Installing ONNX Runtime dependencies..."
curl -sSL https://github.com/microsoft/onnxruntime/releases/download/v1.12.0/onnxruntime-linux-x64-1.12.0.tgz -o onnxruntime-linux-x64-1.12.0.tgz
tar -xf onnxruntime-linux-x64-1.12.0.tgz
mkdir /usr/local/include/onnxruntime
cd onnxruntime-linux-x64-1.12.0
cp -r include/* /usr/local/include/onnxruntime
cp -r lib /usr/local
