/* WARNING: This is a generated file.
 * Any manual changes will be overwritten. */

#include "testnum.h"

/* TestNumber - ns=1;i=2002 */

static UA_StatusCode function_testnum_0_begin(UA_Server *server, UA_UInt16 *ns)
{
    UA_StatusCode retVal = UA_STATUSCODE_GOOD;
    UA_VariableAttributes attr = UA_VariableAttributes_default;
    attr.minimumSamplingInterval = 0.000000;
    attr.userAccessLevel = 1;
    attr.accessLevel = 1;
    /* Value rank inherited */
    attr.valueRank = -2;
    attr.dataType = UA_NODEID_NUMERIC(ns[0], 5LU);
    attr.displayName = UA_LOCALIZEDTEXT("", "TestNumber");
#ifdef UA_ENABLE_NODESET_COMPILER_DESCRIPTIONS
    attr.description = UA_LOCALIZEDTEXT("", "TestNumber");
#endif
    retVal |= UA_Server_addNode_begin(server, UA_NODECLASS_VARIABLE,
                                      UA_NODEID_NUMERIC(ns[1], 2002LU),
                                      UA_NODEID_NUMERIC(ns[0], 85LU),
                                      UA_NODEID_NUMERIC(ns[0], 47LU),
                                      UA_QUALIFIEDNAME(ns[1], "TestNumber"),
                                      UA_NODEID_NUMERIC(ns[0], 63LU),
                                      (const UA_NodeAttributes *)&attr, &UA_TYPES[UA_TYPES_VARIABLEATTRIBUTES], NULL, NULL);
    return retVal;
}

static UA_StatusCode function_testnum_0_finish(UA_Server *server, UA_UInt16 *ns)
{
    return UA_Server_addNode_finish(server, UA_NODEID_NUMERIC(ns[1], 2002LU));
}

UA_StatusCode testnum(UA_Server *server)
{
    UA_StatusCode retVal = UA_STATUSCODE_GOOD;
    /* Use namespace ids generated by the server */
    UA_UInt16 ns[2];
    ns[0] = UA_Server_addNamespace(server, "http://opcfoundation.org/UA/");
    ns[1] = UA_Server_addNamespace(server, "urn:open62541.server.application");

    /* Load custom datatype definitions into the server */
    if ((retVal = function_testnum_0_begin(server, ns)) != UA_STATUSCODE_GOOD)
        return retVal;
    if ((retVal = function_testnum_0_finish(server, ns)) != UA_STATUSCODE_GOOD)
        return retVal;
    return retVal;
}
