if(NOT EXISTS "${CMAKE_ROOT}/Modules/CPack.cmake")
  message(STATUS "CPack is not found. SKIP")
  return()
endif()

set(CPACK_PACKAGE_CONTACT "cv-rmvl community")
set(CPACK_PACKAGE_VERSION_MAJOR "${RMVL_VERSION_MAJOR}")
set(CPACK_PACKAGE_VERSION_MINOR "${RMVL_VERSION_MINOR}")
set(CPACK_PACKAGE_VERSION_PATCH "${RMVL_VERSION_PATCH}")
set(CPACK_PACKAGE_VERSION "${RMVL_VERSION_PLAIN}")
set(CPACK_RESOURCE_FILE_LICENSE "${CMAKE_CURRENT_SOURCE_DIR}/LICENSE")
set(CPACK_RESOURCE_FILE_README "${CMAKE_CURRENT_SOURCE_DIR}/README.md")


if(${CMAKE_SYSTEM_NAME} MATCHES "Linux")
  set(CPACK_GENERATOR "DEB")
elseif(${CMAKE_SYSTEM_NAME} MATCHES "Windows")
  set(CPACK_GENERATOR "NSIS")
endif()

# deb
set(CPACK_DEBIAN_PACKAGE_DEPENDS "build-essential")

include(CPack)