set(RMVL_VERSION_FILE "${CMAKE_CURRENT_SOURCE_DIR}/modules/core/include/rmvl/core/version.hpp")
file(STRINGS "${RMVL_VERSION_FILE}" RMVL_VERSION_PARTS REGEX "#define RMVL_VERSION_[A-Z]+[ ]+" )

string(REGEX REPLACE ".+RMVL_VERSION_MAJOR[ ]+([0-9]+).*" "\\1" RMVL_VERSION_MAJOR "${RMVL_VERSION_PARTS}")
string(REGEX REPLACE ".+RMVL_VERSION_MINOR[ ]+([0-9]+).*" "\\1" RMVL_VERSION_MINOR "${RMVL_VERSION_PARTS}")
string(REGEX REPLACE ".+RMVL_VERSION_PATCH[ ]+([0-9]+).*" "\\1" RMVL_VERSION_PATCH "${RMVL_VERSION_PARTS}")
string(REGEX REPLACE ".+RMVL_VERSION_STATUS[ ]+\"([^\"]*)\".*" "\\1" RMVL_VERSION_STATUS "${RMVL_VERSION_PARTS}")

set(RMVL_VERSION_PLAIN "${RMVL_VERSION_MAJOR}.${RMVL_VERSION_MINOR}.${RMVL_VERSION_PATCH}")

set(RMVL_VERSION "${RMVL_VERSION_PLAIN}${RMVL_VERSION_STATUS}")
set(CMAKE_PROJECT_VERSION "${RMVL_VERSION}")
