name: Build 2.x in Linux

on:
  push:
    branches:
      - 2.x
  pull_request:
    branches:
      - 2.x
  workflow_dispatch:

jobs:
  build-u20:
    name: Ubuntu 20.04 support for amd64
    uses: cv-rmvl/ci-workflow/.github/workflows/rmvl-build-u20.yml@v1
  build-u22:
    name: Ubuntu 22.04 support for amd64
    uses: cv-rmvl/ci-workflow/.github/workflows/rmvl-build-u22.yml@v1
  build-u22-arm:
    name: Ubuntu 22.04 support for aarch64
    uses: cv-rmvl/ci-workflow/.github/workflows/rmvl-build-u22arm.yml@v1
  build-u24:
    name: Ubuntu 24.04 support for amd64
    uses: cv-rmvl/ci-workflow/.github/workflows/rmvl-build-u24.yml@v1
  build-u24-arm:
    name: Ubuntu 24.04 support for aarch64
    uses: cv-rmvl/ci-workflow/.github/workflows/rmvl-build-u24arm.yml@v1
