name: Release in 2.x

on:
  push:
    tags:
      - '2.*'

permissions:
  contents: write

jobs:
  build-u20:
    name: Ubuntu 20.04 support for amd64
    uses: cv-rmvl/ci-workflow/.github/workflows/rmvl-build-u20.yml@v1
  build-u22:
    name: Ubuntu 22.04 support for amd64
    uses: cv-rmvl/ci-workflow/.github/workflows/rmvl-build-u22.yml@v1
  build-u22-arm:
    name: Ubuntu 22.04 support for aarch64
    uses: cv-rmvl/ci-workflow/.github/workflows/rmvl-build-u22arm.yml@v1
  build-u24:
    name: Ubuntu 24.04 support for amd64
    uses: cv-rmvl/ci-workflow/.github/workflows/rmvl-build-u24.yml@v1
  build-u24-arm:
    name: Ubuntu 24.04 support for aarch64
    uses: cv-rmvl/ci-workflow/.github/workflows/rmvl-build-u24arm.yml@v1
  build-win:
    name: Windows support for amd64
    uses: cv-rmvl/ci-workflow/.github/workflows/rmvl-build-win.yml@v1
  build-win-arm:
    name: Windows support for aarch64
    uses: cv-rmvl/ci-workflow/.github/workflows/rmvl-build-winarm.yml@v1
  package-u20:
    name: Package Ubuntu 20.04
    needs: build-u20
    uses: cv-rmvl/ci-workflow/.github/workflows/rmvl-package-u20.yml@v1
  package-u22:
    name: Package Ubuntu 22.04
    needs: build-u22
    uses: cv-rmvl/ci-workflow/.github/workflows/rmvl-package-u22.yml@v1
  package-u22-arm:
    name: Package Ubuntu 22.04 arm64
    needs: build-u22-arm
    uses: cv-rmvl/ci-workflow/.github/workflows/rmvl-package-u22arm.yml@v1
  package-u24:
    name: Package Ubuntu 24.04
    needs: build-u24
    uses: cv-rmvl/ci-workflow/.github/workflows/rmvl-package-u24.yml@v1
  package-u24-arm:
    name: Package Ubuntu 24.04 arm64
    needs: build-u24-arm
    uses: cv-rmvl/ci-workflow/.github/workflows/rmvl-package-u24arm.yml@v1
  package-win:
    name: Package Windows
    needs: build-win
    uses: cv-rmvl/ci-workflow/.github/workflows/rmvl-package-win.yml@v1
  package-win-arm:
    name: Package Windows arm64
    needs: build-win-arm
    uses: cv-rmvl/ci-workflow/.github/workflows/rmvl-package-winarm.yml@v1
  release:
    name: Create Release and Upload Assets
    needs:
      - package-u20
      - package-u22
      - package-u22-arm
      - package-u24
      - package-u24-arm
      - package-win
      - package-win-arm
    uses: cv-rmvl/ci-workflow/.github/workflows/rmvl-release-assets.yml@v1