name: Release in 1.x

on:
  push:
    tags:
      - '1.*'

permissions:
  contents: write

jobs:
  build-u20:
    name: Ubuntu 20.04 support for amd64
    uses: cv-rmvl/ci-workflow/.github/workflows/rmvl-build-u20.yml@v1
  build-u22:
    name: Ubuntu 22.04 support for amd64
    uses: cv-rmvl/ci-workflow/.github/workflows/rmvl-build-u22.yml@v1
  build-u22arm:
    name: Ubuntu 22.04 support for aarch64
    uses: cv-rmvl/ci-workflow/.github/workflows/rmvl-build-u22arm.yml@v1
  release:
    name: Create Release
    needs:
      - build-u20
      - build-u22
      - build-u22arm
    uses: cv-rmvl/ci-workflow/.github/workflows/rmvl-release.yml@v1
