name: Build 2.x in Windows

on:
  push:
    branches:
      - 2.x
  pull_request:
    branches:
      - 2.x
  workflow_dispatch:

jobs:
  windows:
    name: Windows support for amd64
    uses: cv-rmvl/ci-workflow/.github/workflows/rmvl-build-win.yml@v1
  windows-arm:
    name: Windows support for aarch64
    uses: cv-rmvl/ci-workflow/.github/workflows/rmvl-build-winarm.yml@v1
